### ISSUE TITLE
Missing declarative keyword `let`

### ISSUE THREAD

**Issue by alexandresgf** [rothirschtec/Shell-Extensions#1]
Hello,

I found an issue in your code, specifically in the `task_timer.js` file, you just missed putting the declarative keyword `let` before the variable `elapsedTime` on line 359. I fixed it on my computer, but I'm unable to send a PR with the fixed code.

Please, check my PR: https://github.com/rothirschtec/Shell-Extensions/pull/2

**Comment by rothirschtec** [comment]
Done

**Comment by rothirschtec** [comment]
Thanks for your commit : )
